### ISSUE TITLE
Date Overview is still a bit buggy

### ISSUE THREAD

**Issue by david-prv** [ColinTimBarndt/stylus_cms-sic-saarland-theme#1]
G'day,
I'm talking about this page:  
[https://cms.sic.saarland/prog1_21/termine/events/index](https://cms.sic.saarland/prog1_21/termine/events/index)

Especially the page and items-per-page selectors are looking a bit broken, the rest is nice!

**Comment by ColinTimBarndt** [comment]
I've merged your PR, and it fixed most of the pagination style, but the "Items per page" dropdown button appears below the number input. I am not sure why this is the case.
![image](https://user-images.githubusercontent.com/26167910/150554705-322747bd-0e79-45a8-81b6-6a0459006297.png)

**Comment by david-prv** [comment]
it may be because of the width, try checking that

**Comment by david-prv** [comment]
it is because your ``.btn-group`` class has attribute: ``display: flex;``

**Comment by ColinTimBarndt** [comment]
I removed the flex display style and styled the input field like it is done on the Prog1 forum (and how I styled it for the CMS forum) for consistency
